apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  namespace: {{NAMESPACE}}
spec:
  replicas: {{DEFAULT_REPLICAS}}
  revisionHistoryLimit: {{DEFAULT_HISTORY_LIMIT}}
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:1.8.1
        livenessProbe:
          httpGet:
            path: /api/v1/services
            port: 9411
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
          - name: www
            containerPort: 9411
          - name: api
            containerPort: 9410
        env:
          - name: JAVA_OPTS
            value: -Djava.security.egd=file:/dev/./urandom -Xms32m -Xmx32m
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 10Mi