apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zipkin
  namespace: infrastructure
  labels:
    app: zipkin
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: zipkin-tls
    hosts:
      - {{ZIPKIN_HOSTNAME}}
  rules:
  - host: {{ZIPKIN_HOSTNAME}}
    http:
      paths:
      - path: /
        backend:
          serviceName: zipkin
          servicePort: www