apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{NAMESPACE}}
  labels:
    app: zipkin
spec:
  type: NodePort
  ports:
  - name: www
    port: 80
    targetPort: www
    protocol: TCP
  - name: api
    port: 9410
    targetPort: api
    protocol: TCP
  selector:
    app: zipkin