apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-cron
  namespace: infrastructure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-cron
    spec:
      nodeSelector:
        instrumenting: "true"
      containers:
      - name: zipkin-cron
        image: openzipkin/zipkin-dependencies:latest
        command: 
          - "crond"
          - "-f"
        resources:
          limits:
            memory: 20Mi
        env:
          - name: STORAGE_TYPE
            value: "cassandra"
          - name: CASSANDRA_CONTACT_POINTS
            value: "zipkin-cassandra"