kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auth-server
  namespace: infrastructure
  labels:
    app: auth-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi