kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: ""
  name: styx-redis
  namespace: {{NAMESPACE}}
  labels:
    app: styx
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi