apiVersion: v1
kind: Service
metadata:
  name: styx-redis
  namespace: {{NAMESPACE}}
  labels:
    app: styx
    component: redis
spec:
  ports:
  - name: db
    port: 6379
    targetPort: db
    protocol: TCP
  selector:
    app: styx
    component: redis
