apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: prometheus-node-exporter
  namespace: {{NAMESPACE}}
  labels:
    app: prometheus
    component: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: api
      port: 9100
      targetPort: api
      protocol: TCP
  selector:
    app: prometheus
    component: node-exporter
