kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  namespace: {{NAMESPACE}}
  labels:
    app: prometheus
    component: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi