apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: prometheus
  namespace: {{NAMESPACE}}
  labels:
    app: prometheus
    component: core
spec:
  type: NodePort
  ports:
  - name: www
    port: 80
    targetPort: www
    protocol: TCP
  selector:
    app: prometheus
    component: core