apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  namespace: infrastructure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      nodeSelector:
        instrumenting: "true"
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        ports:
          - name: www
            containerPort: 9411
          - name: api
            containerPort: 9410
        resources:
          limits:
            memory: 50Mi
        env:
          - name: STORAGE_TYPE
            value: "cassandra"
          - name: CASSANDRA_CONTACT_POINTS
            value: "zipkin-cassandra"
          - name: SELF_TRACING_ENABLED
            value: "false"