apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: infrastructure
  labels:
    app: zipkin
spec:
  ports:
  - name: www
    port: 80
    targetPort: www
    protocol: TCP
  selector:
    app: zipkin