apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: {{NAMESPACE}}
spec:
  replicas: {{DEFAULT_REPLICAS}}
  revisionHistoryLimit: {{DEFAULT_HISTORY_LIMIT}}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        infrastructure: "true"
      containers:
      - name: grafana
        image: grafana/grafana:3.1.1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        env:
          # This variable is required to setup templates in Grafana.
            # The following env variables are required to make Grafana accessible via
            # the kubernetes api-server proxy. On production clusters, we recommend
            # removing these env variables, setup auth for grafana, and expose the grafana
            # service using a LoadBalancer or a public IP.
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          # - name: GF_SERVER_ROOT_URL
          #   value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
        ports:
        - name: www
          containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana