kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: ""
  name: grafana
  namespace: {{NAMESPACE}}
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi