kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  namespace: {{NAMESPACE}}
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi