apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{NAMESPACE}}
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - name: www
    port: 80
    targetPort: www
    protocol: TCP
  selector:
    app: grafana