apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-cassandra
  namespace: infrastructure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-cassandra
    spec:
      nodeSelector:
        instrumenting: "true"
      containers:
      - name: zipkin-cassandra
        image: openzipkin/zipkin-cassandra:latest
        ports:
          - name: db
            containerPort: 9042
        resources:
          limits:
            memory: 500Mi
        volumeMounts:
            - mountPath: /var/lib/cassandra
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zipkin-cassandra