kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zipkin-cassandra
  namespace: infrastructure
  labels:
    app: zipkin-cassandra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi