apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  revisionHistoryLimit: {{DEFAULT_HISTORY_LIMIT}}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        proxy: "true"
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.2
        name: nginx
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10249
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=infrastructure/default-http-backend
        volumeMounts:
          - mountPath: /etc/nginx/template
            name: template
            readOnly: true
      volumes:
        - name: template
          configMap:
            name: nginx
            items:
            - key: nginx.tmpl
              path: nginx.tmpl