apiVersion: v1
kind: PersistentVolume
metadata:
  name: sm0
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/host-sm0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sm1
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/host-sm1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sm2
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/host-sm2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sm3
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/host-sm3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sm4
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/host-sm4