apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: styx
  namespace: {{NAMESPACE}}
  labels:
    app: styx
    component: core
spec:
  ports:
  - name: debug
    port: 8080
    targetPort: debug
    protocol: TCP
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 8082
    targetPort: grpc
    protocol: TCP
  selector:
    app: styx
    component: core